@@ .. @@
-/*
-  # Hotel Ordering System Database Schema
-  
-  This schema supports a multi-role hotel ordering system with:
-  - User authentication and role management
-  - Menu item management with categories and pricing
-  - Order processing with status tracking
-  - Table session management for servers
-  - Part order workflow for kitchen operations
-  - Company/supplier management
-  - Financial calculations with tax handling
-*/
-
--- Enable UUID extension
-CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-
--- Custom types for better data integrity
-CREATE TYPE user_role AS ENUM ('server', 'kitchen', 'admin', 'customer');
-CREATE TYPE order_status AS ENUM ('pending', 'confirmed', 'preparing', 'ready', 'delivered', 'cancelled');
-CREATE TYPE payment_status AS ENUM ('pending', 'paid', 'failed');
-CREATE TYPE menu_category AS ENUM ('appetizer', 'main', 'dessert', 'beverage');
-CREATE TYPE food_category AS ENUM ('Raw', 'Cooked');
-CREATE TYPE part_order_status AS ENUM ('draft', 'sent_to_kitchen', 'preparing', 'ready', 'served');
-CREATE TYPE table_session_status AS ENUM ('active', 'ready_to_close', 'closed');
-
--- Users table (extends Supabase auth.users)
-CREATE TABLE users (
-  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
-  email TEXT UNIQUE NOT NULL,
-  full_name TEXT NOT NULL,
-  role user_role NOT NULL DEFAULT 'customer',
-  created_at TIMESTAMPTZ DEFAULT NOW()
-);
-
--- Enable RLS
-ALTER TABLE users ENABLE ROW LEVEL SECURITY;
-
--- Users can read own data
-CREATE POLICY "Users can read own data"
-  ON users
-  FOR SELECT
-  TO authenticated
-  USING (uid() = id);
-
--- Companies table for suppliers/vendors
-CREATE TABLE companies (
-  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
-  name TEXT UNIQUE NOT NULL,
-  category TEXT,
-  contact_email TEXT,
-  phone TEXT,
-  created_at TIMESTAMPTZ DEFAULT NOW(),
-  updated_at TIMESTAMPTZ DEFAULT NOW(),
-  deleted_at TIMESTAMPTZ
-);
-
--- Enable RLS
-ALTER TABLE companies ENABLE ROW LEVEL SECURITY;
-
--- All authenticated users can read companies
-CREATE POLICY "Authenticated users can read companies"
-  ON companies
-  FOR SELECT
-  TO authenticated
-  USING (deleted_at IS NULL);
-
--- Only admins can manage companies
-CREATE POLICY "Admins can manage companies"
-  ON companies
-  FOR ALL
-  TO authenticated
-  USING (
-    EXISTS (
-      SELECT 1 FROM users 
-      WHERE users.id = uid() 
-      AND users.role = 'admin'
-    )
-  );
-
--- Menu items table
-CREATE TABLE menu_items (
-  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
-  name TEXT NOT NULL,
-  description TEXT,
-  price DECIMAL(10,2) NOT NULL,
-  category menu_category NOT NULL,
-  company TEXT NOT NULL,
-  tax_rate DECIMAL(5,2) NOT NULL DEFAULT 8.5,
-  food_category food_category NOT NULL DEFAULT 'Cooked',
-  image_url TEXT,
-  available BOOLEAN NOT NULL DEFAULT true,
-  created_at TIMESTAMPTZ DEFAULT NOW(),
-  updated_at TIMESTAMPTZ DEFAULT NOW(),
-  deleted_at TIMESTAMPTZ
-);
-
--- Enable RLS
-ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
-
--- All authenticated users can read available menu items
-CREATE POLICY "Authenticated users can read available menu items"
-  ON menu_items
-  FOR SELECT
-  TO authenticated
-  USING (available = true AND deleted_at IS NULL);
-
--- Only admins can manage menu items
-CREATE POLICY "Admins can manage menu items"
-  ON menu_items
-  FOR ALL
-  TO authenticated
-  USING (
-    EXISTS (
-      SELECT 1 FROM users 
-      WHERE users.id = uid() 
-      AND users.role = 'admin'
-    )
-  );
-
--- Orders table
-CREATE TABLE orders (
-  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
-  customer_id UUID REFERENCES users(id),
-  subtotal DECIMAL(10,2) NOT NULL,
-  tax_amount DECIMAL(10,2) NOT NULL,
-  total_amount DECIMAL(10,2) NOT NULL,
-  status order_status NOT NULL DEFAULT 'pending',
-  payment_status payment_status NOT NULL DEFAULT 'pending',
-  special_instructions TEXT,
-  table_number INTEGER,
-  created_at TIMESTAMPTZ DEFAULT NOW(),
-  updated_at TIMESTAMPTZ DEFAULT NOW(),
-  deleted_at TIMESTAMPTZ
-);
-
--- Enable RLS
-ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
-
--- Users can read their own orders, kitchen and admin can read all
-CREATE POLICY "Users can read own orders, kitchen and admin can read all"
-  ON orders
-  FOR SELECT
-  TO authenticated
-  USING (
-    customer_id = uid() OR
-    EXISTS (
-      SELECT 1 FROM users 
-      WHERE users.id = uid() 
-      AND users.role IN ('kitchen', 'admin', 'server')
-    )
-  );
-
--- Servers and admins can create orders
-CREATE POLICY "Servers and admins can create orders"
-  ON orders
-  FOR INSERT
-  TO authenticated
-  WITH CHECK (
-    EXISTS (
-      SELECT 1 FROM users 
-      WHERE users.id = uid() 
-      AND users.role IN ('server', 'admin')
-    )
-  );
-
--- Kitchen staff and admins can update order status
-CREATE POLICY "Kitchen and admins can update orders"
-  ON orders
-  FOR UPDATE
-  TO authenticated
-  USING (
-    EXISTS (
-      SELECT 1 FROM users 
-      WHERE users.id = uid() 
-      AND users.role IN ('kitchen', 'admin', 'server')
-    )
-  );
-
--- Order items table (junction table)
-CREATE TABLE order_items (
-  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
-  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
-  menu_item_id UUID NOT NULL REFERENCES menu_items(id),
-  quantity INTEGER NOT NULL DEFAULT 1,
-  price DECIMAL(10,2) NOT NULL,
-  created_at TIMESTAMPTZ DEFAULT NOW()
-);
-
--- Enable RLS
-ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
-
--- Users can read order items for their orders, kitchen and admin can read all
-CREATE POLICY "Users can read own order items, kitchen and admin can read all"
-  ON order_items
-  FOR SELECT
-  TO authenticated
-  USING (
-    EXISTS (
-      SELECT 1 FROM orders 
-      WHERE orders.id = order_id 
-      AND (
-        orders.customer_id = uid() OR
-        EXISTS (
-          SELECT 1 FROM users 
-          WHERE users.id = uid() 
-          AND users.role IN ('kitchen', 'admin', 'server')
-        )
-      )
-    )
-  );
-
--- Servers and admins can manage order items
-CREATE POLICY "Servers and admins can manage order items"
-  ON order_items
-  FOR ALL
-  TO authenticated
-  USING (
-    EXISTS (
-      SELECT 1 FROM users 
-      WHERE users.id = uid() 
-      AND users.role IN ('server', 'admin')
-    )
-  );
-
--- Table sessions table (for server workflow)
-CREATE TABLE table_sessions (
-  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
-  table_number INTEGER NOT NULL,
-  customer_name TEXT NOT NULL,
-  server_id UUID REFERENCES users(id),
-  total_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
-  status table_session_status NOT NULL DEFAULT 'active',
-  created_at TIMESTAMPTZ DEFAULT NOW(),
-  updated_at TIMESTAMPTZ DEFAULT NOW(),
-  deleted_at TIMESTAMPTZ
-);
-
--- Enable RLS
-ALTER TABLE table_sessions ENABLE ROW LEVEL SECURITY;
-
--- Servers can read their own sessions, admins can read all
-CREATE POLICY "Servers can read own sessions, admins can read all"
-  ON table_sessions
-  FOR SELECT
-  TO authenticated
-  USING (
-    server_id = uid() OR
-    EXISTS (
-      SELECT 1 FROM users 
-      WHERE users.id = uid() 
-      AND users.role IN ('admin', 'kitchen')
-    )
-  );
-
--- Servers and admins can manage table sessions
-CREATE POLICY "Servers and admins can manage table sessions"
-  ON table_sessions
-  FOR ALL
-  TO authenticated
-  USING (
-    EXISTS (
-      SELECT 1 FROM users 
-      WHERE users.id = uid() 
-      AND users.role IN ('server', 'admin')
-    )
-  );
-
--- Part orders table (individual orders within table sessions)
-CREATE TABLE part_orders (
-  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
-  table_session_id UUID NOT NULL REFERENCES table_sessions(id) ON DELETE CASCADE,
-  items JSONB NOT NULL, -- Store items as JSON for flexibility
-  special_instructions TEXT,
-  status part_order_status NOT NULL DEFAULT 'draft',
-  created_at TIMESTAMPTZ DEFAULT NOW(),
-  printed_at TIMESTAMPTZ,
-  deleted_at TIMESTAMPTZ
-);
-
--- Enable RLS
-ALTER TABLE part_orders ENABLE ROW LEVEL SECURITY;
-
--- Same access as table sessions
-CREATE POLICY "Part orders follow table session access"
-  ON part_orders
-  FOR SELECT
-  TO authenticated
-  USING (
-    EXISTS (
-      SELECT 1 FROM table_sessions ts
-      WHERE ts.id = table_session_id
-      AND (
-        ts.server_id = uid() OR
-        EXISTS (
-          SELECT 1 FROM users 
-          WHERE users.id = uid() 
-          AND users.role IN ('admin', 'kitchen')
-        )
-      )
-    )
-  );
-
--- Servers, kitchen, and admins can manage part orders
-CREATE POLICY "Servers, kitchen, and admins can manage part orders"
-  ON part_orders
-  FOR ALL
-  TO authenticated
-  USING (
-    EXISTS (
-      SELECT 1 FROM users 
-      WHERE users.id = uid() 
-      AND users.role IN ('server', 'admin', 'kitchen')
-    )
-  );
-
--- Indexes for performance
-CREATE INDEX idx_users_email ON users(email);
-CREATE INDEX idx_users_role ON users(role);
-CREATE INDEX idx_menu_items_category ON menu_items(category);
-CREATE INDEX idx_menu_items_available ON menu_items(available);
-CREATE INDEX idx_menu_items_company ON menu_items(company);
-CREATE INDEX idx_orders_customer_id ON orders(customer_id);
-CREATE INDEX idx_orders_status ON orders(status);
-CREATE INDEX idx_orders_payment_status ON orders(payment_status);
-CREATE INDEX idx_orders_table_number ON orders(table_number);
-CREATE INDEX idx_orders_created_at ON orders(created_at);
-CREATE INDEX idx_order_items_order_id ON order_items(order_id);
-CREATE INDEX idx_order_items_menu_item_id ON order_items(menu_item_id);
-CREATE INDEX idx_table_sessions_server_id ON table_sessions(server_id);
-CREATE INDEX idx_table_sessions_table_number ON table_sessions(table_number);
-CREATE INDEX idx_table_sessions_status ON table_sessions(status);
-CREATE INDEX idx_part_orders_table_session_id ON part_orders(table_session_id);
-CREATE INDEX idx_part_orders_status ON part_orders(status);
-
--- Triggers for updated_at timestamps
-CREATE OR REPLACE FUNCTION update_updated_at_column()
-RETURNS TRIGGER AS $$
-BEGIN
-    NEW.updated_at = NOW();
-    RETURN NEW;
-END;
-$$ language 'plpgsql';
-
-CREATE TRIGGER update_companies_updated_at BEFORE UPDATE ON companies FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
-CREATE TRIGGER update_menu_items_updated_at BEFORE UPDATE ON menu_items FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
-CREATE TRIGGER update_orders_updated_at BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
-CREATE TRIGGER update_table_sessions_updated_at BEFORE UPDATE ON table_sessions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
-
--- Business logic functions
-CREATE OR REPLACE FUNCTION calculate_order_totals(order_uuid UUID)
-RETURNS TABLE(subtotal DECIMAL, tax_amount DECIMAL, total_amount DECIMAL) AS $$
-DECLARE
-    item_record RECORD;
-    calc_subtotal DECIMAL := 0;
-    calc_tax DECIMAL := 0;
-    calc_total DECIMAL := 0;
-BEGIN
-    FOR item_record IN
-        SELECT oi.quantity, oi.price, mi.tax_rate
-        FROM order_items oi
-        JOIN menu_items mi ON oi.menu_item_id = mi.id
-        WHERE oi.order_id = order_uuid
-    LOOP
-        calc_subtotal := calc_subtotal + (item_record.quantity * item_record.price);
-        calc_tax := calc_tax + (item_record.quantity * item_record.price * item_record.tax_rate / 100);
-    END LOOP;
-    
-    calc_total := calc_subtotal + calc_tax;
-    
-    RETURN QUERY SELECT calc_subtotal, calc_tax, calc_total;
-END;
-$$ LANGUAGE plpgsql;
-
-CREATE OR REPLACE FUNCTION update_table_session_total()
-RETURNS TRIGGER AS $$
-BEGIN
-    -- This would be implemented based on part_orders changes
-    -- For now, it's a placeholder for future implementation
-    RETURN NEW;
-END;
-$$ LANGUAGE plpgsql;
-
--- Sample data
-INSERT INTO companies (name, category, contact_email, phone) VALUES
-('Lush & Hush', 'Hotel Restaurant', 'orders@lushandhush.com', '+44 20 7123 4567'),
-('Pick D', 'Quick Service', 'orders@pickd.com', '+44 20 7234 5678'),
-('SS Food Court', 'Food Court', 'orders@ssfoodcourt.com', '+44 20 7345 6789'),
-('Fresh Garden Co.', 'Produce & Salads', 'orders@freshgarden.com', '+44 20 7456 7890'),
-('Ocean Fresh Seafood', 'Seafood & Fish', 'orders@oceanfresh.com', '+44 20 7567 8901'),
-('Premium Meats Co.', 'Meat & Poultry', 'sales@premiummeats.co.uk', '+44 20 7678 9012'),
-('Artisan Pizza Works', 'Italian & Pizza', 'info@artisanpizza.co.uk', '+44 20 7789 0123'),
-('Sweet Dreams Bakery', 'Desserts & Pastries', 'orders@sweetdreams.com', '+44 20 7890 1234'),
-('Vineyard Select', 'Wine & Spirits', 'sales@vineyardselect.com', '+44 20 7901 2345'),
-('Local Brew Co.', 'Craft Beer', 'orders@localbrew.co.uk', '+44 20 7012 3456');
-
-INSERT INTO users (email, full_name, role) VALUES
-('server@hotel.com', 'John Smith', 'server'),
-('kitchen@hotel.com', 'Chef Maria', 'kitchen'),
-('admin@hotel.com', 'Manager David', 'admin');
-
-INSERT INTO menu_items (name, description, price, category, company, tax_rate, food_category, available) VALUES
--- Appetizers
-('Caesar Salad', 'Fresh romaine lettuce with parmesan cheese, croutons, and our signature Caesar dressing', 12.99, 'appetizer', 'Fresh Garden Co.', 8.5, 'Raw', true),
-('Buffalo Wings', 'Crispy chicken wings tossed in spicy buffalo sauce, served with blue cheese dip', 14.99, 'appetizer', 'Lush & Hush', 8.5, 'Cooked', true),
-('Truffle Arancini', 'Crispy risotto balls filled with truffle and parmesan, served with marinara sauce', 16.99, 'appetizer', 'Lush & Hush', 8.5, 'Cooked', true),
-('Bruschetta Trio', 'Three varieties of toasted bread with fresh toppings', 11.99, 'appetizer', 'Artisan Pizza Works', 8.5, 'Cooked', true),
-
--- Main Courses
-('Grilled Atlantic Salmon', 'Fresh salmon fillet with lemon herb seasoning, served with roasted vegetables and quinoa', 28.99, 'main', 'Ocean Fresh Seafood', 8.5, 'Cooked', true),
-('Beef Tenderloin', 'Prime cut beef tenderloin cooked to perfection, served with garlic mashed potatoes', 34.99, 'main', 'Premium Meats Co.', 8.5, 'Cooked', true),
-('Lobster Risotto', 'Creamy arborio rice with fresh lobster, asparagus, and white wine reduction', 32.99, 'main', 'Ocean Fresh Seafood', 8.5, 'Cooked', true),
-('Margherita Pizza', 'Wood-fired pizza with fresh mozzarella, basil, and San Marzano tomatoes', 18.99, 'main', 'Artisan Pizza Works', 8.5, 'Cooked', true),
-('Chicken Parmesan', 'Breaded chicken breast with marinara sauce and melted mozzarella', 24.99, 'main', 'Lush & Hush', 8.5, 'Cooked', true),
-('Fish and Chips', 'Beer-battered cod with crispy fries and mushy peas', 19.99, 'main', 'Pick D', 8.5, 'Cooked', true),
-
--- Desserts
-('Chocolate Lava Cake', 'Warm chocolate cake with molten center, served with vanilla ice cream', 8.99, 'dessert', 'Sweet Dreams Bakery', 8.5, 'Cooked', true),
-('Tiramisu', 'Traditional Italian dessert with coffee-soaked ladyfingers and mascarpone', 9.99, 'dessert', 'Sweet Dreams Bakery', 8.5, 'Raw', true),
-('Crème Brûlée', 'Classic French custard with caramelized sugar crust and fresh berries', 10.99, 'dessert', 'Sweet Dreams Bakery', 8.5, 'Cooked', true),
-('Cheesecake', 'New York style cheesecake with berry compote', 7.99, 'dessert', 'Sweet Dreams Bakery', 8.5, 'Raw', true),
-
--- Beverages
-('House Wine (Glass)', 'Selection of premium red or white wine from our curated collection', 8.99, 'beverage', 'Vineyard Select', 10.0, 'Raw', true),
-('Craft Beer', 'Local brewery selection featuring seasonal and signature brews', 6.99, 'beverage', 'Local Brew Co.', 10.0, 'Raw', true),
-('Fresh Orange Juice', 'Freshly squeezed orange juice from premium Valencia oranges', 4.99, 'beverage', 'Fresh Garden Co.', 8.5, 'Raw', true),
-('Artisan Coffee', 'Single-origin coffee beans expertly roasted and brewed to perfection', 3.99, 'beverage', 'Lush & Hush', 8.5, 'Cooked', true),
-('Sparkling Water', 'Premium sparkling water with lemon', 2.99, 'beverage', 'Lush & Hush', 8.5, 'Raw', true),
-('Signature Cocktail', 'House special cocktail with premium spirits', 12.99, 'beverage', 'Lush & Hush', 10.0, 'Raw', true);
+-- =====================================================
+-- Hotel Ordering System - PostgreSQL Database Schema
+-- Streamlined for Current Application Functionality
+-- =====================================================
+
+-- This schema file now points to the optimized PostgreSQL schema
+-- Please use database/postgresql-schema.sql for the complete setup
+
+\echo 'Please run database/postgresql-schema.sql instead'
+\echo 'This file provides a streamlined PostgreSQL schema optimized for the current application functionality'