@@ .. @@
-/*
-  # Hotel Ordering System Database Schema
-  
-  1. New Tables
-    - `users` - User profiles extending Supabase auth
-    - `companies` - Supplier/vendor information  
-    - `menu_items` - Restaurant menu with pricing and categories
-    - `orders` - Customer orders with status tracking
-    - `order_items` - Junction table for orders and menu items
-    - `table_sessions` - Server workflow for part orders
-    - `part_orders` - Individual orders within table sessions
-
-  2. Security
-    - Enable RLS on all tables
-    - Add policies for authenticated users based on roles
-    - Server role can create/manage orders
-    - Kitchen role can view/update order status  
-    - Admin role has full access
-    - Customer role can view own orders
-
-  3. Sample Data
-    - Companies with contact information
-    - Menu items across all categories with realistic pricing
-    - Sample users for each role
-*/
-
--- Enable required extensions
-CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-
--- Create custom types
-CREATE TYPE user_role AS ENUM ('server', 'kitchen', 'admin', 'customer');
-CREATE TYPE order_status AS ENUM ('pending', 'confirmed', 'preparing', 'ready', 'delivered', 'cancelled');
-CREATE TYPE payment_status AS ENUM ('pending', 'paid', 'failed');
-CREATE TYPE menu_category AS ENUM ('appetizer', 'main', 'dessert', 'beverage');
-CREATE TYPE food_category AS ENUM ('Raw', 'Cooked');
-CREATE TYPE session_status AS ENUM ('active', 'ready_to_close', 'closed');
-CREATE TYPE part_order_status AS ENUM ('draft', 'sent_to_kitchen', 'preparing', 'ready', 'served');
-
--- Users table (extends Supabase auth.users)
-CREATE TABLE IF NOT EXISTS users (
-  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
-  email text UNIQUE NOT NULL,
-  full_name text NOT NULL,
-  role user_role NOT NULL DEFAULT 'customer',
-  password_hash text NOT NULL,
-  last_login timestamptz,
-  created_at timestamptz DEFAULT now()
-);
-
-ALTER TABLE users ENABLE ROW LEVEL SECURITY;
-
-CREATE POLICY "Users can read own data"
-  ON users
-  FOR SELECT
-  TO authenticated
-  USING (auth.uid() = id);
-
--- Companies table
-CREATE TABLE IF NOT EXISTS companies (
-  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
-  name text UNIQUE NOT NULL,
-  category text,
-  contact_email text,
-  phone text,
-  address text,
-  created_at timestamptz DEFAULT now(),
-  updated_at timestamptz DEFAULT now(),
-  deleted_at timestamptz
-);
-
-ALTER TABLE companies ENABLE ROW LEVEL SECURITY;
-
-CREATE POLICY "Anyone can read companies"
-  ON companies
-  FOR SELECT
-  TO authenticated
-  USING (deleted_at IS NULL);
-
-CREATE POLICY "Admins can manage companies"
-  ON companies
-  FOR ALL
-  TO authenticated
-  USING (
-    EXISTS (
-      SELECT 1 FROM users 
-      WHERE id = auth.uid() 
-      AND role = 'admin'
-    )
-  );
-
--- Menu items table
-CREATE TABLE IF NOT EXISTS menu_items (
-  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
-  name text NOT NULL,
-  description text,
-  price decimal(10,2) NOT NULL CHECK (price >= 0),
-  category menu_category NOT NULL,
-  company text NOT NULL,
-  tax_rate decimal(5,2) NOT NULL DEFAULT 8.5 CHECK (tax_rate >= 0 AND tax_rate <= 100),
-  food_category food_category NOT NULL DEFAULT 'Cooked',
-  image_url text,
-  available boolean NOT NULL DEFAULT true,
-  created_at timestamptz DEFAULT now(),
-  updated_at timestamptz DEFAULT now(),
-  deleted_at timestamptz
-);
-
-ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
-
-CREATE POLICY "Anyone can read available menu items"
-  ON menu_items
-  FOR SELECT
-  TO authenticated
-  USING (available = true AND deleted_at IS NULL);
-
-CREATE POLICY "Admins can manage menu items"
-  ON menu_items
-  FOR ALL
-  TO authenticated
-  USING (
-    EXISTS (
-      SELECT 1 FROM users 
-      WHERE id = auth.uid() 
-      AND role = 'admin'
-    )
-  );
-
--- Orders table
-CREATE TABLE IF NOT EXISTS orders (
-  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
-  customer_id uuid NOT NULL REFERENCES auth.users(id),
-  subtotal decimal(10,2) NOT NULL CHECK (subtotal >= 0),
-  tax_amount decimal(10,2) NOT NULL CHECK (tax_amount >= 0),
-  total_amount decimal(10,2) NOT NULL CHECK (total_amount >= 0),
-  status order_status NOT NULL DEFAULT 'pending',
-  payment_status payment_status NOT NULL DEFAULT 'pending',
-  special_instructions text,
-  table_number integer,
-  created_at timestamptz DEFAULT now(),
-  updated_at timestamptz DEFAULT now(),
-  deleted_at timestamptz
-);
-
-ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
-
-CREATE POLICY "Users can read own orders"
-  ON orders
-  FOR SELECT
-  TO authenticated
-  USING (
-    customer_id = auth.uid() 
-    OR EXISTS (
-      SELECT 1 FROM users 
-      WHERE id = auth.uid() 
-      AND role IN ('kitchen', 'admin')
-    )
-  );
-
-CREATE POLICY "Servers and admins can create orders"
-  ON orders
-  FOR INSERT
-  TO authenticated
-  WITH CHECK (
-    EXISTS (
-      SELECT 1 FROM users 
-      WHERE id = auth.uid() 
-      AND role IN ('server', 'admin')
-    )
-  );
-
-CREATE POLICY "Kitchen and admins can update order status"
-  ON orders
-  FOR UPDATE
-  TO authenticated
-  USING (
-    EXISTS (
-      SELECT 1 FROM users 
-      WHERE id = auth.uid() 
-      AND role IN ('kitchen', 'admin')
-    )
-  );
-
--- Order items table
-CREATE TABLE IF NOT EXISTS order_items (
-  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
-  order_id uuid NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
-  menu_item_id uuid NOT NULL REFERENCES menu_items(id),
-  quantity integer NOT NULL CHECK (quantity > 0),
-  price decimal(10,2) NOT NULL CHECK (price >= 0),
-  created_at timestamptz DEFAULT now()
-);
-
-ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
-
-CREATE POLICY "Users can read order items for accessible orders"
-  ON order_items
-  FOR SELECT
-  TO authenticated
-  USING (
-    EXISTS (
-      SELECT 1 FROM orders o
-      WHERE o.id = order_id
-      AND (
-        o.customer_id = auth.uid()
-        OR EXISTS (
-          SELECT 1 FROM users u
-          WHERE u.id = auth.uid()
-          AND u.role IN ('kitchen', 'admin')
-        )
-      )
-    )
-  );
-
-CREATE POLICY "Servers and admins can manage order items"
-  ON order_items
-  FOR ALL
-  TO authenticated
-  USING (
-    EXISTS (
-      SELECT 1 FROM users 
-      WHERE id = auth.uid() 
-      AND role IN ('server', 'admin')
-    )
-  );
-
--- Table sessions table
-CREATE TABLE IF NOT EXISTS table_sessions (
-  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
-  table_number integer NOT NULL,
-  customer_name text NOT NULL,
-  total_amount decimal(10,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
-  status session_status NOT NULL DEFAULT 'active',
-  payment_status payment_status DEFAULT 'pending',
-  created_at timestamptz DEFAULT now(),
-  updated_at timestamptz DEFAULT now(),
-  closed_at timestamptz
-);
-
-ALTER TABLE table_sessions ENABLE ROW LEVEL SECURITY;
-
-CREATE POLICY "Servers and admins can manage table sessions"
-  ON table_sessions
-  FOR ALL
-  TO authenticated
-  USING (
-    EXISTS (
-      SELECT 1 FROM users 
-      WHERE id = auth.uid() 
-      AND role IN ('server', 'admin')
-    )
-  );
-
-CREATE POLICY "Kitchen can read table sessions"
-  ON table_sessions
-  FOR SELECT
-  TO authenticated
-  USING (
-    EXISTS (
-      SELECT 1 FROM users 
-      WHERE id = auth.uid() 
-      AND role IN ('kitchen', 'server', 'admin')
-    )
-  );
-
--- Part orders table
-CREATE TABLE IF NOT EXISTS part_orders (
-  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
-  table_session_id uuid NOT NULL REFERENCES table_sessions(id) ON DELETE CASCADE,
-  table_number integer NOT NULL,
-  items jsonb NOT NULL,
-  special_instructions text,
-  status part_order_status NOT NULL DEFAULT 'draft',
-  created_at timestamptz DEFAULT now(),
-  updated_at timestamptz DEFAULT now(),
-  printed_at timestamptz
-);
-
-ALTER TABLE part_orders ENABLE ROW LEVEL SECURITY;
-
-CREATE POLICY "Servers and admins can manage part orders"
-  ON part_orders
-  FOR ALL
-  TO authenticated
-  USING (
-    EXISTS (
-      SELECT 1 FROM users 
-      WHERE id = auth.uid() 
-      AND role IN ('server', 'admin')
-    )
-  );
-
-CREATE POLICY "Kitchen can read and update part orders"
-  ON part_orders
-  FOR ALL
-  TO authenticated
-  USING (
-    EXISTS (
-      SELECT 1 FROM users 
-      WHERE id = auth.uid() 
-      AND role IN ('kitchen', 'server', 'admin')
-    )
-  );
-
--- Create indexes for performance
-CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
-CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
-CREATE INDEX IF NOT EXISTS idx_menu_items_category ON menu_items(category);
-CREATE INDEX IF NOT EXISTS idx_menu_items_available ON menu_items(available);
-CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON orders(customer_id);
-CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
-CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);
-CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
-CREATE INDEX IF NOT EXISTS idx_table_sessions_status ON table_sessions(status);
-CREATE INDEX IF NOT EXISTS idx_part_orders_table_session_id ON part_orders(table_session_id);
-CREATE INDEX IF NOT EXISTS idx_part_orders_status ON part_orders(status);
-
--- Create views for common queries
-CREATE OR REPLACE VIEW order_details AS
-SELECT 
-  o.*,
-  u.full_name as customer_name,
-  u.email as customer_email,
-  json_agg(
-    json_build_object(
-      'id', oi.id,
-      'menu_item_id', oi.menu_item_id,
-      'quantity', oi.quantity,
-      'price', oi.price,
-      'menu_item', json_build_object(
-        'id', mi.id,
-        'name', mi.name,
-        'description', mi.description,
-        'category', mi.category,
-        'company', mi.company,
-        'tax_rate', mi.tax_rate,
-        'food_category', mi.food_category
-      )
-    )
-  ) as order_items
-FROM orders o
-LEFT JOIN auth.users u ON o.customer_id = u.id
-LEFT JOIN order_items oi ON o.id = oi.order_id
-LEFT JOIN menu_items mi ON oi.menu_item_id = mi.id
-WHERE o.deleted_at IS NULL
-GROUP BY o.id, u.full_name, u.email;
-
-CREATE OR REPLACE VIEW menu_items_with_company AS
-SELECT 
-  mi.*,
-  c.category as company_category,
-  c.contact_email as company_email,
-  c.phone as company_phone
-FROM menu_items mi
-LEFT JOIN companies c ON mi.company = c.name
-WHERE mi.deleted_at IS NULL;
-
--- Insert sample data
-
--- Sample companies
-INSERT INTO companies (name, category, contact_email, phone) VALUES
-('Lush & Hush', 'Hotel Restaurant', 'orders@lushandhush.com', '+44 20 7123 4567'),
-('Pick D', 'Quick Service', 'orders@pickd.com', '+44 20 7234 5678'),
-('SS Food Court', 'Food Court', 'orders@ssfoodcourt.com', '+44 20 7345 6789'),
-('Fresh Garden Co.', 'Produce & Salads', 'orders@freshgarden.com', '+44 20 7456 7890'),
-('Ocean Fresh Seafood', 'Seafood & Fish', 'orders@oceanfresh.com', '+44 20 7567 8901'),
-('Premium Meats Co.', 'Meat & Poultry', 'sales@premiummeats.co.uk', '+44 20 7678 9012'),
-('Artisan Pizza Works', 'Italian & Pizza', 'info@artisanpizza.co.uk', '+44 20 7789 0123'),
-('Sweet Dreams Bakery', 'Desserts & Pastries', 'orders@sweetdreams.com', '+44 20 7890 1234'),
-('Vineyard Select', 'Wine & Spirits', 'sales@vineyardselect.com', '+44 20 7901 2345'),
-('Local Brew Co.', 'Craft Beer', 'orders@localbrew.co.uk', '+44 20 7012 3456')
-ON CONFLICT (name) DO NOTHING;
-
--- Sample users (password is 'password123' hashed)
-INSERT INTO users (email, full_name, role, password_hash) VALUES
-('server@hotel.com', 'John Smith', 'server', '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj/VcSAg/9qm'),
-('kitchen@hotel.com', 'Chef Maria', 'kitchen', '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj/VcSAg/9qm'),
-('admin@hotel.com', 'Manager David', 'admin', '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj/VcSAg/9qm')
-ON CONFLICT (email) DO NOTHING;
-
--- Sample menu items
-INSERT INTO menu_items (name, description, price, category, company, tax_rate, food_category, available) VALUES
--- Appetizers
-('Caesar Salad', 'Fresh romaine lettuce with parmesan cheese, croutons, and our signature Caesar dressing', 12.99, 'appetizer', 'Fresh Garden Co.', 8.5, 'Raw', true),
-('Buffalo Wings', 'Crispy chicken wings tossed in spicy buffalo sauce, served with blue cheese dip', 14.99, 'appetizer', 'Lush & Hush', 8.5, 'Cooked', true),
-('Truffle Arancini', 'Crispy risotto balls filled with truffle and parmesan, served with marinara sauce', 16.99, 'appetizer', 'Lush & Hush', 8.5, 'Cooked', true),
-('Bruschetta Trio', 'Three varieties of toasted bread with tomato basil, mushroom, and olive tapenade', 11.99, 'appetizer', 'Artisan Pizza Works', 8.5, 'Cooked', true),
-
--- Main Courses  
-('Grilled Atlantic Salmon', 'Fresh salmon fillet with lemon herb seasoning, served with roasted vegetables and quinoa', 28.99, 'main', 'Ocean Fresh Seafood', 8.5, 'Cooked', true),
-('Beef Tenderloin', 'Prime cut beef tenderloin cooked to perfection, served with garlic mashed potatoes', 34.99, 'main', 'Premium Meats Co.', 8.5, 'Cooked', true),
-('Lobster Risotto', 'Creamy arborio rice with fresh lobster, asparagus, and white wine reduction', 32.99, 'main', 'Ocean Fresh Seafood', 8.5, 'Cooked', true),
-('Margherita Pizza', 'Wood-fired pizza with fresh mozzarella, basil, and San Marzano tomatoes', 18.99, 'main', 'Artisan Pizza Works', 8.5, 'Cooked', true),
-('Chicken Parmesan', 'Breaded chicken breast with marinara sauce and melted mozzarella, served with pasta', 24.99, 'main', 'Lush & Hush', 8.5, 'Cooked', true),
-('Vegetarian Curry', 'Aromatic curry with seasonal vegetables, chickpeas, and basmati rice', 19.99, 'main', 'SS Food Court', 8.5, 'Cooked', true),
-
--- Desserts
-('Chocolate Lava Cake', 'Warm chocolate cake with molten center, served with vanilla ice cream', 8.99, 'dessert', 'Sweet Dreams Bakery', 8.5, 'Cooked', true),
-('Tiramisu', 'Traditional Italian dessert with coffee-soaked ladyfingers and mascarpone', 9.99, 'dessert', 'Sweet Dreams Bakery', 8.5, 'Raw', true),
-('Crème Brûlée', 'Classic French custard with caramelized sugar crust and fresh berries', 10.99, 'dessert', 'Sweet Dreams Bakery', 8.5, 'Cooked', true),
-('Cheesecake', 'New York style cheesecake with berry compote', 7.99, 'dessert', 'Sweet Dreams Bakery', 8.5, 'Raw', true),
-
--- Beverages
-('House Wine (Glass)', 'Selection of premium red or white wine from our curated collection', 8.99, 'beverage', 'Vineyard Select', 10.0, 'Raw', true),
-('Craft Beer', 'Local brewery selection featuring seasonal and signature brews', 6.99, 'beverage', 'Local Brew Co.', 10.0, 'Raw', true),
-('Fresh Orange Juice', 'Freshly squeezed orange juice from premium Valencia oranges', 4.99, 'beverage', 'Fresh Garden Co.', 8.5, 'Raw', true),
-('Artisan Coffee', 'Single-origin coffee beans expertly roasted and brewed to perfection', 3.99, 'beverage', 'Lush & Hush', 8.5, 'Cooked', true),
-('Sparkling Water', 'Premium sparkling water with lemon or lime', 2.99, 'beverage', 'Lush & Hush', 8.5, 'Raw', true),
-('Signature Cocktail', 'House special cocktail crafted by our mixologist', 12.99, 'beverage', 'Lush & Hush', 10.0, 'Raw', true)
-ON CONFLICT DO NOTHING;
+-- This file has been replaced with postgresql-schema.sql
+-- Please use database/postgresql-schema.sql for the complete PostgreSQL schema